### ISSUE TITLE
Add contact info

### ISSUE THREAD

**Issue by daytonmills** [wiserim/phaser-raycaster#1]
Hello wiserim,

Thank you for making this project! I'm finding it very useful.
Could you add your contact info to GitHub so I could send you an email with some feedback and questions I have? Also may have an opportunity for you if interested.

Sorry for opening an issue, no other way to reach out to you :p

**Comment by wiserim** [comment]
Hello Dayton,

Thank you for your feedback. I'm happy that someone find it helpfull.

I still have a few things to settle, so for now you can contact me at <a href="mailto:marcin_walczak2@o2.pl">marcin_walczak2@o2.pl</a>.
