### ISSUE TITLE
How to import this plugin to phaser!?

### ISSUE THREAD

**Issue by reagentJS** [wiserim/phaser-raycaster#12]
Hello.
I installed this plugin via npm, but it doesnt't work:
![image](https://user-images.githubusercontent.com/64849722/105642019-15e06700-5e98-11eb-845f-b66bebb5b8f1.png)
Can you help me?

**Comment by wiserim** [comment]
Hello,
From what I see its seem you haven't imported phaser-raycaster plugin.
You can do that by adding code below:
`import PhaserRaycaster from  'phaser-raycaster';`
