### ISSUE TITLE
How to increase the limit of the ray?

### ISSUE THREAD

**Issue by javurtez** [wiserim/phaser-raycaster#23]
Hello, how can I increase the limit of the ray instead of basing it on the scale of the game? For example, I have a config setting of:
```
scale: {
    parent: "content",
    scaleMode: Phaser.Scale.WIDTH_CONTROLS_HEIGHT,
    autoCenter: Phaser.Scale.CENTER_VERTICALLY,
    width: 560,
    height: 1212,
  },
```
If the player position x is greater than the scaleWidth, like player position x is 565, it would limit the result of intersection x. The pink dots are the intersection limit which 560 even though there are no colliders/mappedobjects nearby.

How can I solve this since there are no docs regarding this issue?

![firefox_I7UF3vClqT](https://user-images.githubusercontent.com/11276316/161710088-176f49ce-36b7-446a-9e53-c7186741f96a.png)

**Comment by wiserim** [comment]
Hello @javurtez,
Similar issue was already posted in issue #22.

By default raycaster sets it's bounding box on position (0, 0) and size of canvas resolution.
In case of larger, scrollable scenes, you have to set it manually.

```javascript
//set bounding box on raycaster creation
var raycaster = this.raycasterPlugin.createRaycaster({
  boundingBox: this.worldLayer.getBounds() //get scene's world bounding box (arcade physics)
});

//set bounding box after creation
raycaster.setBoundingBox(x, y, width, height);
```
Docs:
- [Raycaster constructor](https://wiserim.github.io/phaser-raycaster/Raycaster.html#Raycaster__anchor)
- [Raycaster.setBoundingBox()](https://wiserim.github.io/phaser-raycaster/Raycaster.html#setBoundingBox__anchor)

**Comment by javurtez** [comment]
Thank you so much. It is working fine now.

Also, I'm sorry for the duplicate issue.
