### ISSUE TITLE
Add in methods for ray and raycaster destruction

### ISSUE THREAD

**Issue by CodestarGames** [wiserim/phaser-raycaster#26]
In my game I'm spawning a few rays for hitbox detection and I'd love to have some convenience methods for destroying them. Right now I'm not sure of the proper way to clean up my raycasts and physics objects linked to those ray casts other than deleting the physics body and graphics objects manually. Even then I'm not sure if there are still objects hanging around in memory linked to the ray itself.

**Comment by wiserim** [comment]
I've published version `0.10.3`.
It adds `Raycaster.destroy()`, `Map.destroy()` and `Ray.destroy()` methods.
Additionally `Raycaster.removeMappedObjects` method now also destroys Map objects.
