### ISSUE TITLE
TS typings

### ISSUE THREAD

**Issue by ahvonenj** [wiserim/phaser-raycaster#31]
**Is your feature request related to a problem? Please describe.**

Raycaster plugin doesn't seem to have TS typings, which results in a lot of guesswork:

![image](https://user-images.githubusercontent.com/8504168/177777064-81a9f8d0-9e4c-414b-b6f9-26898a49707a.png)

As well as annoying (but fortunately non-breaking) errors:

![image](https://user-images.githubusercontent.com/8504168/177776133-26a433bd-6f3d-4e09-941b-52be80d98b04.png)

**Describe the solution you'd like**

I would like to get TS typings for the raycaster plugin.

**Describe alternatives you've considered**

The plugin seems to already have JSDoc style comments. I wonder if those could be automatically converted to TS typings somehow.

**Additional context**

If possible, it would be for the best if the typings were built-in and not a separate package like "@types/phaser-raycast-plugin". Or if someone happens to know about these things more than me and can make it work easily, why not. I just feel that this whole electron + phaser + typescript + webpack + plugin combinations is already pretty complicated.

**Comment by wiserim** [comment]
Hello,
I didn't plan to convert plugin to TypeScript.
I'll consider it in the future, when I'll have more free time.

**Comment by ahvonenj** [comment]
Good enough for me, thanks for considering!

**Comment by nlucis** [comment]
> Hello, I didn't plan to convert plugin to TypeScript. I'll consider it in the future, when I'll have more free time.

Would strongly recommend considering as Phaser 4 will be Typescript only.

**Comment by wiserim** [comment]
TypeScript typings has been added in version `0.10.5`.

**Comment by ahvonenj** [comment]
> TypeScript typings has been added in version `0.10.5`.

A huge thank you for taking the time and having the interest to do this! I don't have time right now to test it out, but will do so at some point. :)

Your plugin is very useful for any kind of serious Phaser development and with the added TS-support, it is damn near perfect! You've done a lot of work to make this happen and I really appreciate it!

Changes in version `0.10.5` resolve this issue.
