### ISSUE TITLE
Plugin should destroy debug graphics of raycasts that get destroyed.

### ISSUE THREAD

**Issue by CodestarGames** [wiserim/phaser-raycaster#36]
As far as I can tell, rays, raycasters, and maps can be destroyed now, but the debug graphics that they use still remain in the scene after they are destroyed.

![image](https://user-images.githubusercontent.com/5861090/214998425-ea7ca932-1b34-43a4-97ce-7d35d674a824.png)

**Comment by wiserim** [comment]
Hello,
Thank you for reporting this bug.
`Ray.destroy()` method doesn't destroy graphics object it's using to draw in debug mode.
The same goes to `Raycaster.destroy()`.

I've started working on major update for plugin, but I should be able to deliver bug fixes soon.

**Comment by wiserim** [comment]
I've published version `0.10.6`.
It includes fixes for reported bugs.

**Comment by CodestarGames** [comment]
Thanks! That fix removed the debug graphics upon the destroy method being called. Although, I'm also using the debug flag in arcade physics to show the bodies and it seems the physics bodies don't get removed unless I remove them manually myself before I call the destroy method on rays.

**Comment by wiserim** [comment]
Raycaster doesn't destroy any game objects or physics bodies.
It only destroys `Raycaster.Map` objects assigned to them.

[Docs: Raycaster.removeMappedObjects()](https://wiserim.github.io/phaser-raycaster/Raycaster.html#removeMappedObjects__anchor)
[Codepen Example](https://codepen.io/wiserim/pen/wvxxVme)
