### ISSUE TITLE
Raycaster.Map.destroy() doesn't work for Arcade and Matter bodies

### ISSUE THREAD

**Issue by dreasgrech** [wiserim/phaser-raycaster#39]
The `Raycaster.Map#destroy` function throws an `object is not defined` error:

![image](https://github.com/wiserim/phaser-raycaster/assets/501697/2e287e51-d034-425a-a089-8e9b8cceb110)

**To Reproduce**
After adding objects with `mapGameObjects(gameObjects)`, call `raycaster.removeMappedObjects(gameObjects);`

**The fix**
https://github.com/wiserim/phaser-raycaster/blob/1d6541e1f07f96ad543e35057f06aa0b155cc2bc/src/map/destroy.js#L12
Change `delete object.raycasterMap;` to `delete this.object.raycasterMap;`

**Comment by dreasgrech** [comment]
Opened pull request https://github.com/wiserim/phaser-raycaster/pull/40

**Comment by wiserim** [comment]
Thank you for finding the bug and fixing it.
I've added your fix to dev branch and I'll ship it with next release.

**Comment by wiserim** [comment]
Version 0.10.7 has been released
Pull request: #42
