### ISSUE TITLE
Does not work with upcoming phaser 3.50.0

### ISSUE THREAD

**Issue by koljakutschera** [wiserim/phaser-raycaster#5]
Hi, 

Just want to warn you that it does not work with the actual phaser beta (3.50.0-beta.9). This may be a bug in phaser but I think its short before stable release.

Maybe worth a look... for a quick scan just: npm i phaser@3.50.0-beta.9

Thank you for this awesome plugin. Saved me a lot of time!!!

**Comment by wiserim** [comment]
Thank you for informing about the issue.
Can you provide error logs and/or sample code to replicate errors you encountered?
I would help with debugging.

**Comment by wiserim** [comment]
I couldn't find any issue with Phaser-raycaster with Pahaser 3.50.0.
I'm closing the issue due to lack of information about it or way to replicate it.
