### ISSUE TITLE
Feature request: Matter Physics

### ISSUE THREAD

**Issue by koljakutschera** [wiserim/phaser-raycaster#6]
What about Matter Physics? It would be great to make this work both with matter and arcade physics. If you could give a quick overview of what needs to be changed to make this work with matter ill happily have a look by myself. Thank you!

**Comment by wiserim** [comment]
I considered implementing Matter Physics for quite some time.
I'll need to study this physics library first. Then I'll be able to decide which if it'll be better to implement it into plugin, or prepare separate one with similar API.
I haven't much free time to work on it, but I'll  try to do some research on it when I'll got one.

**Comment by wiserim** [comment]
#7 
v0.9.0 now supports matter physics.
